---
- name: Copy over login banner file
  template:
    src: motd.j2
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root

- name: Copy warning file
  copy:
    src: login.warn
    dest: /etc/login.warn
    mode: 0644
    owner: root
    group: root

- name: Copy warning file
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    mode: 0755
    owner: root
    group: root

- name: remove old
  file:
    path: /etc/profile.d/motd.sh
    state: absent