---
- name: "Copy warning file (pre-login)"
  copy:
    src: login.warn
    dest: /etc/login.warn
    mode: 0644
    owner: root
    group: root

- name: "Copy over login banner file (post-login)"
  template:
    src: motd.j2
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root
