---
- name: Copy over login banner file
  template:
    src: motd.j2
    dest: /etc/motd.j2
    mode: 0644
    owner: root
    group: root

- name: Copy warning file
  copy:
    src: login.warn
    dest: /etc/login.warn
    mode: 0644
    owner: root
    group: root