---
- name: "update"
  import_tasks: updates.yml

- name: "profile"
  import_tasks: profile.yml

- name: "banner"
  import_tasks: banner.yml

- name: "ssh"
  import_tasks: ssh.yml

- name: "kubernetes requirements"
  import_tasks: kubernetes-requirements.yml