---
- name: "Only execute on tasks that have the correct tag"
  when: "'base' in hostvars[inventory_hostname].proxmox_tags_parsed"
  block:
    - name: "update"
      include_tasks: updates.yml

    - name: "profile"
      include_tasks: profile.yml

    - name: "banner"
      include_tasks: banner.yml

    - name: "ssh"
      include_tasks: ssh.yml

    - name: "general packages"
      include_tasks: packages.yml