---
# tasks file for base
- name: run profile tasks
  import_tasks: updates.yml

- name: run profile tasks
  import_tasks: bash.yml

- name: run profile tasks
  import_tasks: banner.yml

#- name: run profile tasks
#  import_tasks: kubernetes.yml

- name: run profile tasks
  import_tasks: profile.yml

- name: run ssh tasks
  import_tasks: ssh.yml

- name: run network tasks
  import_tasks: network.yml
