---
- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: "update"
  import_tasks: updates.yml

- name: "profile"
  import_tasks: profile.yml

- name: "banner"
  import_tasks: banner.yml

- name: "ssh"
  import_tasks: ssh.yml

- name: "general packages"
  import_tasks: packages.yml