---
- name: "Only execute on tasks that have the correct tag"
  block:
    - name: "update"
      include_tasks: updates.yml

    - name: "banner"
      include_tasks: banner.yml

    - name: "SSH configuration"
      include_tasks: ssh.yml