---
- name: "base configuration"
  block:
    - name: "update"
      include_tasks: updates.yml

    - name: "banner"
      include_tasks: banner.yml

    - name: "ssh"
      include_tasks: ssh.yml

    - name: "tools"
      include_tasks: tools.yml
