---
- name: "Only execute on tasks that have the correct tag"
  block:
    - name: "What's going on?"
      debug:
        var: default(proxmox_net0.ip)

    - name: "update"
      include_tasks: updates.yml

    - name: "profile"
      include_tasks: profile.yml

    - name: "banner"
      include_tasks: banner.yml

    - name: "ssh"
      include_tasks: ssh.yml

    - name: "general packages"
      include_tasks: packages.yml