---
- name: "base configuration"
  block:
    - name: "update"
      include_tasks: updates.yml

    - name: "banner"
      include_tasks: banner.yml

    - name: "SSH configuration"
      include_tasks: ssh.yml
