---
- name: "Install NFS packages"
  dnf:
    name: nfs-utils
    state: present

- name: "Create volume group"
  lvg:
    vg: edinburgh_slow
    pvs: /dev/sdb

- name: "Create logical volume"
  lvol:
    vg: edinburgh_slow
    lv: data
    size: +100%FREE

- name: "Create filesystem"
  filesystem:
    dev: /dev/edinburgh_slow/data
    fstype: xfs

- name: "Create mount points"
  file:
    path: /mnt/edinburgh-slow
    state: directory
    owner: root
    group: root
    mode: 0777

- name: "Mount volume"
  mount:
    src: /dev/edinburgh_slow/data
    path: /mnt/edinburgh-slow
    fstype: xfs
    state: mounted

- name: "Ensure NFS server is active"
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: "Setup exports"
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart-nfs-server