---
- name: "Add Ceph Helm repository"
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "ceph-csi"
    repo_url: "{{ ceph_helm_repository }}"

- name: "Install Ceph RBD"
  include_tasks: ceph_rbd.yml

- name: "Install Ceph snapshot capabilities"
  include_tasks: snapshots.yml

- name: "Wait for ceph pods to be ready"
  become: true
  become_user: kubernetes
  when: ceph_wait_for_pods_to_be_ready
  command: "kubectl wait --for=condition=Ready pods --all -n {{ ceph_rbd_namespace }} --timeout=20m"
  changed_when: false
