---
- name: Create snapshot CRDs directory
  file:
    path: /tmp/kubernetes_snapshot_crd
    state: directory
    owner: kubernetes
    group: kubernetes
    mode: 0770

- name: Download snapshot CRDs
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/tmp/kubernetes_snapshot_crd"
    owner: kubernetes
    group: kubernetes
    mode: 0660
  loop: "{{ ceph_snapshot_crds }}"

- name: Create snapshot CRDs
  become: true
  become_user: kubernetes
  register: ceph_snapshot_crd_result
  until: ceph_snapshot_crd_result.rc == 0
  retries: 12
  delay: 10
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop: "{{ ceph_snapshot_crds_download_locations }}"

- name: Create snapshot class
  become: true
  become_user: kubernetes
  register: ceph_snapshot_class_result
  until: ceph_snapshot_class_result.rc == 0
  retries: 12
  delay: 10
  k8s:
    state: present
    resource_definition: "{{ lookup('file', 'snapshot-class.yml') | from_yaml }}"
