---
- name: "GitHub user"
  user:
    name: "{{ runner_user }}"
    group: "{{ runner_user }}"
    shell: /bin/bash
    expires: -1

- name: "Install basic tools"
  dnf:
    name:
      - dos2unix

- name: "Enable Ansible repository"
  rhsm_repository:
    name: ansible-2.9-for-rhel-8-x86_64-rpms
    state: enabled

- name: "Install Ansible"
  dnf:
    name:
      - ansible

- name: "Enable Terraform repository"
  yum_repository:
    name: "hashicorp"
    description: "Hashicorp repository"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"

- name: "Install Hashicorp tools"
  dnf:
    name:
      - terraform
      - packer