---
- hosts: linux
  become: true
  tasks:
    - name: Set banner in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "Banner /etc/ssh/login_banner"

    - name: Copy over banner file
      file:
        path: /etc/ssh/login_banner
        state: absent

    - name: Copy over login banner file
      copy:
        src: issue.net
        dest: /etc/issue.net
      notify: sshd restart

    - name: Copy over MOTD script
      copy:
        src: 00-clinch-banner.sh
        dest: /etc/update-motd.d/00-clinch-banner.sh
        owner: root
        group: root
        mode: 0755

  handlers:
    - name: sshd restart
      tasks:
        service:
          - name: sshd
            state: restarted