---
- hosts: ubuntu
  become: yes
  tasks:
    - name: "Build hosts file"
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.1.10 truenas"
        - "192.168.1.12	darling"
        - "192.168.1.13	mandela"
        - "192.168.1.14	turing"

    - name: "Remove old host lines"
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: absent
      loop:
        - "192.168.1.10 freenas"