---
- name: Install metricbeat
  hosts: ubuntu
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.15.0
    beat: metricbeat
    beat_conf:
      metricbeat:
        metricbeat.config.modules:
          path: ${path.config}/modules.d/*.yml
          reload.enabled: false
        setup.template.settings:
          index.number_of_shards: 1
          index.codec: best_compression
        setup.kibana:
          host: "http://192.168.1.14:31732"
        output.elasticsearch:
          hosts: [ "http://192.168.1.14:32577" ]
        processors:
          - add_host_metadata: ~
          - add_cloud_metadata: ~
          - add_docker_metadata: ~
          - add_kubernetes_metadata: ~
