---
- name: Add flannel chart repository
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "flannel"
    repo_url: "{{ flannel_helm_repository_url }}"

- name: Install flannel
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: "{{ flannel_namespace }}"
    create_namespace: true
    values:
      podCidr: "{{ pod_network_cidr }}"
  register: "flannel_install"

- name: Add label to namespace
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ flannel_namespace }}"
    definition:
      metadata:
        labels:
          "pod-security.kubernetes.io/enforce": "privileged"

- name: "Wait for flannel pods to be ready"
  when: flannel_wait_for_pods_to_be_ready and flannel_install.changed
  become: true
  become_user: kubernetes
  command: "kubectl wait --for=condition=Ready pods --all -n {{ flannel_namespace }} --timeout=10m"
  changed_when: false
