---
- name: Add flannel chart repository
  become: true
  become_user: kubernetes
  register: flannel_helm_install
  kubernetes.core.helm_repository:
    name: "flannel"
    repo_url: "{{ flannel_helm_repository_url }}"

- name: Install flannel
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: "{{ flannel_namespace }}"
    create_namespace: true
    values:
      podCidr: "{{ pod_network_cidr }}"
  notify:
    - "restart coredns pods"

# https://github.com/clincha/clincha/issues/107
- name: "Reset the Kubernetes network bridges"
  block:
    - name: "Delete the connections"
      nmcli:
        state: absent
        conn_name: "{{ item }}"
      loop:
        - "cni0"
        - "flannel.1"

    - name: "Restart the kubernetes services"
      service:
        state: restarted
        name: "{{ item }}"
      loop:
        - "podman"
        - "kubelet"

- name: Add label to namespace
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ flannel_namespace }}"
    definition:
      metadata:
        labels:
          "pod-security.kubernetes.io/enforce": "privileged"

- meta: flush_handlers

- name: "Wait for flannel pods to be ready"
  become: true
  become_user: kubernetes
  when: flannel_wait_for_pods_to_be_ready
  command: "kubectl wait --for=condition=Ready pods --all -n {{ flannel_namespace }} --timeout=10m"
  changed_when: false
