---
- name: Add flannel chart repository
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "flannel"
    repo_url: "{{ flannel_helm_repository_url }}"

- name: Install flannel
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: "{{ flannel_namespace }}"
    create_namespace: true
    values:
      podCidr: "{{ pod_network_cidr }}"
  notify:
    - restart kube-dns pods

- name: Add label to namespace
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ flannel_namespace }}"
    definition:
      metadata:
        labels:
          "pod-security.kubernetes.io/enforce": "privileged"
