---
- include_tasks: install_flannel.yml
  when: "'kubernetes_master' in group_names"

# https://github.com/clincha/clincha/issues/107
- name: "Reset the Kubernetes network bridges"
  block:
    - name: "Down the connections"
      command:
        cmd: "ip link set {{ item }} down"
      loop:
        - "cni0"
        - "flannel.1"

    - name: "Delete the connections"
      command:
        cmd: "ip link delete {{ item }}"
      loop:
        - "cni0"
        - "flannel.1"

    - name: "Restart the kubernetes services"
      service:
        state: restarted
        name: "{{ item }}"
      loop:
        - "podman"
        - "kubelet"
