- name: Get all pods in kube-system namespace
  k8s_info:
    kind: Pod
    namespace: kube-system
  register: kube_system_pods

- name: Restart core-dns pods
  k8s:
    kind: Pod
    namespace: kube-system
    name: "{{ item }}"
    state: absent
  loop: "{{ kube_system_pods | select('regex', 'coredns') | list }}"
