---
- name: "Add Velero Helm repository"
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "vmware-tanzu"
    repo_url: "https://vmware-tanzu.github.io/helm-charts/"

- name: Install Velero
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: velero
    chart_ref: vmware-tanzu/velero
    release_namespace: velero
    create_namespace: true
    values:
      initContainers:
        - name: velero-plugin-for-azure
          image: velero/velero-plugin-for-microsoft-azure:v1.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
        - name: velero-plugin-for-csi
          image: velero/velero-plugin-for-csi:v0.5.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      configuration:
        backupStorageLocation:
          - name: velero
            provider: azure
            default: true
            bucket: production
            accessMode: ReadWrite
            config:
              resourceGroup: velero
              subscriptionId: c6ff6270-64cf-40d6-ae87-e11cca58de61
              storageAccount: clinchavelero
#        volumeSnapshotLocation:
#          - name: velero
#            provider: azure
#            bucket: production
#            config:
#              resourceGroup: velero
#              subscriptionId: c6ff6270-64cf-40d6-ae87-e11cca58de61
#              storageAccount: clinchavelero
        defaultVolumesToFsBackup: true
      credentials:
        secretContents:
          cloud: |
            AZURE_TENANT_ID=5bdbf6b9-7155-49e5-a3ce-f265fd5ec77e
            AZURE_SUBSCRIPTION_ID=c6ff6270-64cf-40d6-ae87-e11cca58de61
            AZURE_CLIENT_ID=8a84109a-b36b-4d5f-a8c4-f87cf82e5bc6
            AZURE_CLIENT_SECRET={{ lookup('env', 'AZURE_CLIENT_SECRET') }}
            AZURE_RESOURCE_GROUP=velero
            AZURE_CLOUD_NAME=AzurePublicCloud
      snapshotsEnabled: false
      deployNodeAgent: true
      nodeAgent:
        dnsConfig:
          options:
            - name: ndots
              value: "1"

- name: "Check Velero version"
  command:
    cmd: velero version
  failed_when: false
  changed_when: false
  become: true
  become_user: kubernetes
  register: velero_version_output

- name: "Install Velero CLI"
  when:
    - velero_version_output.rc != 0
    - velero_version in velero_version_output.stdout_lines
  block:
    - name: "Get Velero CLI from GitHub"
      get_url:
        url: "https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz"
        dest: "/tmp/velero-{{ velero_version }}-linux-amd64.tar.gz"
        checksum: "md5:09b92fd0baebbcafd850044cd35f6be1"

    - name: "Extract Velero binary"
      unarchive:
        remote_src: true
        src: "/tmp/velero-{{ velero_version }}-linux-amd64.tar.gz"
        dest: "/tmp"

    - name: "Move the Velero binary to the binaries directory"
      copy:
        remote_src: true
        src: "/tmp/velero-{{ velero_version }}-linux-amd64/velero"
        dest: "/usr/bin/velero"
        mode: 0755

    - name: "Tidy up"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/velero-{{ velero_version }}-linux-amd64.tar.gz"
        - "/tmp/velero-{{ velero_version }}-linux-amd64"


