- name: "Create volume group"
  lvg:
    vg: "vg{{ item.index }}"
    pvs: "{{ item }}"
  with_items: configuration_volumes

- name: "Create logical volume"
  lvol:
    vg: "vg{{ item.index }}"
    lv: "lv{{ item.index }}"
    size: +100%FREE
  with_items: configuration_volumes

- name: "Create filesystem"
  filesystem:
    dev: "/dev/vg{{ item.index }}/lv{{ item.index }}"
    fstype: xfs
  with_items: configuration_volumes

- name: "Create mount points"
  file:
    path: "/mnt/disks/{{ item.index }}"
    state: directory
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
    mode: "{{ mount_mode }}"
  with_items: configuration_volumes

- name: "Mount volume"
  mount:
    src: "/dev/vg{{ item.index }}/lv{{ item.index }}"
    path: "{{ mount_path }}"
    fstype: xfs
    state: mounted
  with_items: configuration_volumes