---
- name: "Initialise cluster"
  command:
    cmd: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_output

- name: "Ensure .kube directory exists"
  file:
    path: "/home/kubernetes/.kube"
    state: directory
    mode: 0770
    owner: "kubernetes"
    group: "kubernetes"

- name: "Symlink kubectl admin.conf to /home/kubernetes/.kube/conf"
  file:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubernetes/.kube/config
    state: link
    owner: "kubernetes"
    group: "kubernetes"
