- name: "Create volume group"
  lvg:
    vg: "vg{{ index }}"
    pvs: "{{ item }}"
  loop: "{{ configuration_volumes }}"
  loop_control:
    index_var: index

- name: "Create logical volume"
  lvol:
    vg: "vg{{ index }}"
    lv: "lv{{ index }}"
    size: +100%FREE
  loop: "{{ configuration_volumes }}"
  loop_control:
    index_var: index

- name: "Create filesystem"
  filesystem:
    dev: "/dev/vg{{ index }}/lv{{ index }}"
    fstype: xfs
  loop: "{{ configuration_volumes }}"
  loop_control:
    index_var: index

- name: "Create mount points"
  file:
    path: "/mnt/disks/{{ index }}"
    state: directory
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
    mode: "{{ mount_mode }}"
  loop: "{{ configuration_volumes }}"
  loop_control:
    index_var: index

- name: "Mount volume"
  mount:
    src: "/dev/vg{{ index }}/lv{{ index }}"
    path: "{{ mount_path }}"
    fstype: xfs
    state: mounted
  loop: "{{ configuration_volumes }}"
  loop_control:
    index_var: index