- name: Join node to Kubernetes master
  command:
    cmd: "{{ kubernetes_join_command }}"
    creates: "/etc/kubernetes/kubelet.conf"

- name: Ensure the workers can communicate through the firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ worker_ports }}"
  notify: reload_firewall
