---
- name: Enable masquerading on firewalld
  firewalld:
    masquerade: true
    permanent: true
    state: enabled
  register: firewalld_worker_node_masquerading

- name: Ensure the workers can communicate through the firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ worker_ports }}"
  register: firewalld_worker_node

- name: reload_firewall
  when: firewalld_worker_node.changed or firewalld_worker_node_masquerading.changed
  systemd:
    name: firewalld
    state: reloaded

- name: Join node to Kubernetes master
  command:
    cmd: "{{ kubernetes_join_command }}"
    creates: "/etc/kubernetes/kubelet.conf"
