---
- name: "Create modprobe config file"
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: 0755

- name: "Run modprobe commands"
  command: modprobe -v {{ item }}
  with_items: "{{ containerd_modprobe_modules }}"
  register: modprobe_output
  changed_when: "'insmod' in modprobe_output.stdout"

- name: "Add sysctl parameters"
  sysctl:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ containerd_sysctl_parameters }}"





