---
- name: "Create modprobe config file"
  template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0755

- name: "Run modprobe commands"
  command: modprobe -v {{ item }}
  with_items: "{{ modprobe_modules }}"
  register: modprobe_output
  changed_when: "'insmod' in modprobe_output.stdout"

- name: "Add sysctl parameters"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value}} "
    state: "{{ item.state }}"
  with_items: "{{ sysctl_parameters }}"

- name: "Add cri-o libraries repository"
  yum_repository:
    name: "devel_kubic_libcontainers_stable"
    file: "devel:kubic:libcontainers:stable.repo"
    description: "Stable Releases of Upstream github.com/containers packages (CentOS_8)"
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
    gpgcheck: true
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/repodata/repomd.xml.key
    enabled: true

- name: "Add cri-o repositories"
  yum_repository:
    name: "devel_kubic_libcontainers_stable_cri-o_1.21"
    file: "devel:kubic:libcontainers:stable:cri-o:1.21.repo"
    description: "devel:kubic:libcontainers:stable:cri-o:1.21 (CentOS_8)"
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8/
    gpgcheck: true
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/CentOS_8/repodata/repomd.xml.key
    enabled: true

- name: "Install cri-o"
  dnf:
    name: cri-o
    state: present

- name: "Start and enable cri-o"
  systemd:
    name: cri-o
    state: started
    enabled: yes
