#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  selinux:
#    policy: targeted
#    state: permissive
#  register: selinux_mode
#
#- name: Reboot if necessary
#  when: selinux_mode.changed
#  reboot:
