---
- name: Disable IPv6
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv6.conf.all.disable_ipv6'
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    state: present
  notify:
    - Restart Networking
