- name: "Initialise the cluster"
  command:
    cmd: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_output

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644