---
- name: "Add kubernetes repositories"
  yum_repository:
    name: "kubernetes"
    file: "kubernetes.repo"
    description: "Kubernetes"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: "Install kubernetes packages"
  dnf:
    name: [ "kubeadm-{{ kubernetes_version }}", "kubelet-{{ kubernetes_version }}", "kubectl-{{ kubernetes_version }}" ]
    state: present
    allow_downgrade: yes
    disable_excludes: kubernetes

- name: "Start and enable the kubelet"
  systemd:
    name: kubelet
    state: started
    enabled: true

- name: "Check if Helm is installed"
  command:
    cmd: "helm version"
  register: helm_version_check
  changed_when: false
  failed_when: false

- name: "Install Helm"
  when: helm_version_check.rc != 0
  block:
    - name: "Download Helm"
      get_url:
        url: https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz
        checksum: "sha256:c12d2cd638f2d066fec123d0bd7f010f32c643afdf288d39a4610b1f9cb32af3"
        dest: /tmp/
      register: helm_download

    - name: "Decompress Helm"
      unarchive:
        remote_src: true
        src: "{{ helm_download.dest }}"
        dest: /tmp/
      register: helm_unarchive

    - name: "Move Helm binary to binary location"
      copy:
        remote_src: true
        src: "{{ helm_unarchive.dest }}/linux-amd64/helm"
        dest: /usr/bin/helm
        mode: 0755
        owner: root
        group: root

# Bugfix - https://github.com/clincha/clinch-home/issues/50
- name: "Ensure containers-common is compatible"
  block:
    - name: "Install versionlock"
      dnf:
        name: python3-dnf-plugin-versionlock
        state: present

    - name: "Lock containers-common version"
      lineinfile:
        path: /etc/dnf/plugins/versionlock.list
        line: containers-common-2:1-39.module+el8.6.0+16891+aaa3bd4c.*
        state: present
        create: false

    - name: "Install compatible version of containers-common"
      dnf:
        name: containers-common-2:1-39.module+el8.6.0+16891+aaa3bd4c
        state: present
        allow_downgrade: true