---
- name: "Add kubernetes repositories"
  yum_repository:
    name: "kubernetes"
    file: "kubernetes.repo"
    description: "Kubernetes"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: >
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: "Install kubernetes packages"
  dnf:
    name:
      - "kubeadm-{{ kubernetes_version }}"
      - "kubelet-{{ kubernetes_version }}"
      - "kubectl-{{ kubernetes_version }}"
    state: present
    allow_downgrade: true
    disable_excludes: kubernetes

- name: "Install kubernetes pip package"
  become: true
  become_user: kubernetes
  pip:
    name: kubernetes
    state: present
    version: 26.1.0
    extra_args: --user

- name: "Start and enable the kubelet"
  systemd:
    name: kubelet
    state: started
    enabled: true
