---
- name: "Add kubernetes repositories"
  yum_repository:
    name: "kubernetes"
    file: "kubernetes.repo"
    description: "Kubernetes"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: "Install kubernetes packages"
  dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - "kubeadm-{{ kubernetes_version }}"
    - "kubelet-{{ kubernetes_version }}"
    - "kubectl-{{ kubernetes_version }}"

- name: "Start and enable the kubelet"
  systemd:
    name: kubelet
    state: started
    enabled: true