---
- name: "Ensure yum repository is setup"
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    src: kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: "Install kubernetes packages"
  dnf:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "kubeadm"
    - "kubelet"
    - "kubectl"