---
- name: "Disable SWAP"
  include_tasks: disable-swap.yml

- name: "Install dependencies"
  dnf:
    name: [ iproute-tc, nfs-utils ]
    state: present

- name: "Install container runtime"
  include_tasks: crio.yml

- name: "kubernetes requirements"
  import_tasks: kubernetes.yml

- name: "Initialise cluster on master node"
  when: "'kubernetes_master' in group_names"
  include_tasks: initialise_master.yml

- name: "Get the kubeadm join command from the master"
  command: kubeadm token create --print-join-command
  changed_when: false
  when: "'kubernetes_master' in group_names"
  register: kubernetes_join_command_result

- name: "Set the kubeadm join command on workers"
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['kubernetes_worker'] }}"

- name: "Setup worker nodes"
  when: "'kubernetes_worker' in group_names"
  include_tasks: configure_worker.yml

- name: "Configure pod networking"
  when: "'kubernetes_master' in group_names"
  include_tasks: pod_networking.yml

- name: "Configure storage"
  when: "'kubernetes_master' in group_names"
  include_tasks: storage.yml

- name: "Setup helpful tools"
  when: "'kubernetes_master' in group_names"
  include_tasks: helpful-tools.yml
