---
- name: "Install container runtime"
  include_tasks: containerd.yml

- name: "Initialise cluster on master node"
  when: kubernetes_role == 'master'
  include_tasks: initialise_master.yml

#- name: "Setup slave nodes"
#  when: kubernetes_role == 'slave'
#  include_tasks: configure_slave.yml