- name: Add flannel chart repository
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "v0.22.0"
    repo_url: "https://flannel-io.github.io/flannel/"

- name: Install flannel
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel
    release_namespace: kube-flannel
    create_namespace: true
    values:
      podCidr: "{{ pod_network_cidr }}"

- name: Add label to namespace
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: kube-flannel
    definition:
      metadata:
        labels:
          "pod-security.kubernetes.io/enforce": "privileged"
