---
- name: "Add Ceph Helm repository"
  become: true
  become_user: kubernetes
  kubernetes.core.helm_repository:
    name: "ceph-csi"
    repo_url: "https://ceph.github.io/csi-charts"

- name: Install Ceph
  become: true
  become_user: kubernetes
  kubernetes.core.helm:
    name: ceph-csi-rbd
    chart_ref: ceph-csi/ceph-csi-rbd
    release_namespace: ceph-csi-rbd
    create_namespace: true
    values:
      csiConfig:
        - clusterID: "c61ed9ad-0a71-4f66-8d6a-b76fd0a47798"
          monitors:
            - "192.168.1.11:6789"
            - "192.168.1.12:6789"
            - "192.168.1.13:6789"
      provisioner:
        enableHostNetwork: true
        httpMetrics:
          enabled: false
      secret:
        create: true
        name: csi-rbd-secret
        userID: admin
        userKey: "{{ lookup('env', 'CEPH_KEY') }}"

- name: Create storage classes
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('file', 'storage-classes.yml') | from_yaml_all }}"

- name: Create snapshot CRDs directory
  file:
    path: /tmp/kubernetes_snapshot_crd
    state: directory
    owner: kubernetes
    group: kubernetes
    mode: 0770

- name: Download snapshot CRDs
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/tmp/kubernetes_snapshot_crd"
    owner: kubernetes
    group: kubernetes
    mode: 0660
  loop:
    - "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml"
    - "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml"
    - "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml"
    - "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.2/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml"
    - "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml"

- name: Create snapshot CRDs
  become: true
  become_user: kubernetes
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "/tmp/kubernetes_snapshot_crd/snapshot.storage.k8s.io_volumesnapshots.yaml"
    - "/tmp/kubernetes_snapshot_crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml"
    - "/tmp/kubernetes_snapshot_crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml"
    - "/tmp/kubernetes_snapshot_crd/rbac-snapshot-controller.yaml"
    - "/tmp/kubernetes_snapshot_crd/setup-snapshot-controller.yaml"

- name: Create snapshot class
  become: true
  become_user: kubernetes
  k8s:
    state: present
    resource_definition: "{{ lookup('file', 'snapshot-class.yml') | from_yaml }}"
