---
- hosts: kubernetes_master
  become: yes
  tasks:
    - name: Create Kubernetes folder in home directory
      file:
        path: /home/clincha/Kubernetes
        state: directory

    - name: Copy Calico init files to Kubernetes folder
      copy:
        dest: /home/clincha/Kubernetes/calico.yml
        src: ../../Kubernetes/Configuration/calico/calico.yaml

    - name: Copy kubeadm bootstrap files to Kubernetes folder
      copy:
        dest: /home/clincha/Kubernetes/ClusterConfiguration.yml
        src: ../../Kubernetes/Configuration/kubeadm/ClusterConfiguration.yaml

    - name: Check if kubeadm is already bootstrapped
      stat:
        path: /etc/kubernetes/controller-manager.conf
      register: kubeadm_bootstrapped

    - name: Initialise Kubernetes cluster
      shell: |
        kubeadm init \
            --config=/home/clincha/Kubernetes/ClusterConfiguration.yml
      when: not kubeadm_bootstrapped.stat.exists

    - name: Create .kube folder in home directory
      file:
        path: /home/clincha/.kube
        state: directory

    - name: Copy admin configuration to .kube folder for clincha
      copy:
        dest: /home/clincha/.kube/config
        src: /etc/kubernetes/admin.conf
        remote_src: yes
        group: clincha
        owner: clincha

    - name: Apply Calico network to cluster
      shell: |
        kubectl apply -f /home/clincha/Kubernetes/calico.yml
      become: yes
      become_user: clincha