---
# Installs Calico on a Kubernetes cluster.
- name: Get Calico helm repo
  become: true
  become_user: kubernetes
  when: "'kubernetes_master' in group_names"
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: "https://docs.tigera.io/calico/charts"

- name: Install Calico using Helm
  become: true
  become_user: kubernetes
  when: "'kubernetes_master' in group_names"
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    create_namespace: true
    values:
      tigeraOperator:
        image: tigera/operator
        version: v1.30.4
        registry: quay.io
      calicoctl:
        image: calico/ctl
        tag: v3.26.1
        registry: quay.io
  register: calico_install
#  until: calico_install.failed is false
#  retries: 3
