---
# Installs Calico on a Kubernetes cluster.

- name: Get Calico helm repo
  become: true
  become_user: kubernetes
  when: "'kubernetes_master' in group_names"
  kubernetes.core.helm_repository:
    name: "calico"
    repo_url: "https://docs.tigera.io/calico/charts"

- name: Install Calico using Helm
  become: true
  become_user: kubernetes
  when: "'kubernetes_master' in group_names"
  kubernetes.core.helm:
    name: tigera-operator
    chart_ref: projectcalico/tigera-operator
    release_namespace: calico-system
    create_namespace: true
  register: calico_install
  until: calico_install.failed is false
  retries: 3
