---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  strategy: { }
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - image: clincha/nginx-proxy
          name: nginx-proxy
          resources: { }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80