---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  strategy: { }
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - image: lscr.io/linuxserver/wireguard
          name: wireguard
          resources: { }
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
            - name: SERVERURL
              value: "clinch-home.com"
            - name: SERVERPORT
              value: "51820"
            - name: PEERS
              value: "1"
            - name: PEERDNS
              value: "auto"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE

---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      name: vpn
      port: 51820
      targetPort: 51820