---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy: { }
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.14.0
          name: elasticsearch
          resources: { }
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: esport
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: esport2
      port: 9300
      targetPort: 9300