---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy: { }
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: kibana:7.14.0
          name: kibana
          resources: { }
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://192.168.1.13:32577
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601