plugin: "community.general.proxmox"
url: "https://192.168.1.11:8006"
user: "root@pam"
validate_certs: false
want_facts: true
compose:
  ansible_host: proxmox_ipconfig0.ip | ipaddr('address')
  proxmox_tags: proxmox_tags_parsed