plugin: "community.general.proxmox"
url: "https://192.168.1.12:8006/"
user: "ansible@pve"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false
compose:
  ansible_host: proxmox_ipconfig0.ip | replace('/24', '')
  site: "'bristol'"
groups:
  base: "'base' in (proxmox_tags_parsed|list)"
  kube-control-plane: "'kubernetes_master' in (proxmox_tags_parsed|list)"
  etcd: "'kubernetes_master' in (proxmox_tags_parsed|list)"
  kube-node: "'kubernetes_worker' in (proxmox_tags_parsed|list)"
  k8s-cluster: "'kubernetes_worker' in (proxmox_tags_parsed|list) or 'kubernetes_master' in (proxmox_tags_parsed|list)"
