plugin: "community.general.proxmox"
url: "https://192.168.1.12:8006/"
user: "root@pam"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false
compose:
  ansible_host: proxmox_ipconfig0.ip | replace('/24', '')
  site: "'bristol'"
groups:
  base: "'base' in (proxmox_tags_parsed|list)"
  kubernetes_master: "'kubernetes_master' in (proxmox_tags_parsed|list)"
  kubernetes_worker: "'kubernetes_worker' in (proxmox_tags_parsed|list)"
