roles: []

collections:
  - name: "community.general"
    version: "6.1.0"
    type: "galaxy"
    source: "https://galaxy.ansible.com"

  - name: "ansible.posix"
    version: "1.5.2"
    type: "galaxy"
    source: "https://galaxy.ansible.com"
