all:
  children:
    bristol:
      hosts:
        darling:
          server_hostname: darling
          ansible_host: 192.168.1.12
        mandela:
          server_hostname: mandela
          ansible_host: 192.168.1.13
        turing:
          server_hostname: turing
          ansible_host: 192.168.1.14
    edinburgh:
      hosts:
#        geddes-01:
#          server_hostname: geddes-01
#          ansible_host: 192.168.1.202
#          kubernetes_role: master
#        geddes-02:
#          server_hostname: geddes-02
#          ansible_host: 192.168.1.180
#          kubernetes_role: node
        edi-s-01:
          server_hostname: edi-s-01
          ansible_host: 192.168.1.174
          kubernetes_role: master
          ansible_user: root
          ansible_password: "Zxj2Q$JyNh7P5@Ne"