all:
  children:
    hawkfield:
      hosts:
        mandela:
          ansible_host: clinch-home.com
          ansible_port: 2222
          ansible_user: ansible
          server_hostname: BRI-C-01
    geddes:
      hosts:
        edi-s-01:
          ansible_host: 192.168.1.174
          kubernetes_role: master
          ansible_user: ansible
          server_hostname: EDI-S-01
