- name: Install requirements
  hosts: kube-control-plane:kube-node
  tasks:
    - name: "Install required packages"
      package:
        name:
          - iproute-tc
        state: present

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
