- name: Requirements
  hosts: k8s_cluster
  tasks:
    - name: Install required packages
      package:
        name:
          - iproute-tc
        state: present

    - name: Disable the firewall
      service:
        name: firewalld
        state: stopped
        enabled: no

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
