- name: Setup github runners
  hosts: github_runner
  become: true
  vars:
    - runner_user: github
    - install_tools: true
  roles:
    - role: github-runner

- name: Setup kubernetes runners
  hosts: kubernetes_master
  become: true
  vars:
    - runner_user: kubernetes
    - install_tools: false
  roles:
    - role: github-runner

- name: Setup repository - clincha
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: clincha
    - runner_user: github
    - runner_dir: /usr/local/bin/actions-runner
    - runner_labels:
        - "{{ site }}"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup repository - streaming (ansible)
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: streaming
    - runner_user: github
    - runner_dir: /usr/local/bin/streaming-runner
    - runner_labels:
        - "{{ site }}"
        - "github-runner"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup repository - streaming (kubernetes)
  hosts: kubernetes_master
  become: true
  vars:
    - github_account: clincha
    - github_repo: streaming
    - runner_user: kubernetes
    - runner_dir: /usr/local/bin/github-runner
    - runner_labels:
        - "{{ site }}"
        - "kubernetes"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup repository - elastic-star (kubernetes)
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: clincha
    - runner_user: github
    - runner_dir: /usr/local/bin/actions-runner
    - runner_labels:
        - "{{ site }}"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup repository - proxy (kubernetes)
  hosts: kubernetes_master
  become: true
  vars:
    - github_account: clincha
    - github_repo: proxy
    - runner_user: kubernetes
    - runner_dir: /usr/local/bin/github-runner-proxy-kubernetes
    - runner_labels:
        - "{{ site }}"
        - "kubernetes"
  roles:
    - role: monolithprojects.github_actions_runner
