- name: Apply base roll
  hosts: proxmox_all_running
  when: "'kubernetes-worker' in hostvars[inventory_hostname].proxmox_tags_parsed"
  become: true
  roles:
    - role: base
#
#- name: Setup storage arrays
#  hosts: storage
#  become: true
#  roles:
#    - role: storage
#
#- name: Kubernetes
#  hosts: hawkfield
#  become: true
#  roles:
#    - role: kubernetes