- name: Apply base roll
  hosts: base
  become: true
  strategy: free
  roles:
    - role: base

- name: Setup github runners
  hosts: github_runner
  become: true
  strategy: free
  roles:
    - role: github-runner

- name: Kubernetes
  hosts: kubernetes_worker
  become: true
  strategy: free
  roles:
    - role: kubernetes