- name: Apply base roll
  hosts: all
  gather_facts: true
  strategy: free
  become: true
  roles:
    - role: base

- name: Setup Edinburgh Kubernetes cluster
  hosts: edinburgh
  gather_facts: true
  strategy: free
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes