- name: Apply base roll
  hosts: all
  gather_facts: true
  strategy: free
  become: true
  roles:
    - role: base

- name: Setup storage arrays
  hosts: storage
  strategy: free
  become: true
  roles:
    - role: ahharu.mdadm

#- name: Kubernetes
#  hosts: hawkfield
#  strategy: free
#  become: true
#  roles:
#    - geerlingguy.docker
#    - geerlingguy.kubernetes
#  vars:
#    kubernetes_allow_pods_on_master: true