- name: Apply base roll
  hosts: base
  become: true
  roles:
    - role: base

- name: Setup github runners
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: clinch-home
    - runner_user: github
    - runner_dir: /usr/local/bin/actions-runner
    - runner_labels:
        - "{{ site }}"
  roles:
    - role: github-runner
    - role: monolithprojects.github_actions_runner

- name: NFS servers
  hosts: nfs_server
  become: true
  roles:
    - role: nfs-server

- name: Kubernetes
  hosts: kubernetes_worker
  become: true
  roles:
    - role: kubernetes