- name: Apply base roll
  hosts: base
  become: true
  roles:
    - role: users
    - role: sudoers
    - role: base

- name: Kubernetes
  hosts: kubernetes_worker
  become: true
  roles:
    - role: kubernetes
