- name: Apply teardown role
  hosts: all:!proxmox_nodes:!github
  become: true
  strategy: free
  roles:
    - role: teardown

- name: Setup github runners
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: clinch-home
    - runner_state: absent
    - runner_user: github
    - runner_dir: /usr/local/bin/actions-runner
    - runner_labels:
        - "{{ site }}"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup github runners (streaming-github-runner)
  hosts: github_runner
  become: true
  vars:
    - github_account: clincha
    - github_repo: streaming
    - runner_state: absent
    - runner_user: github
    - runner_dir: /usr/local/bin/streaming-runner
    - runner_labels:
        - "{{ site }}"
        - "github-runner"
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup github runners (streaming-kubernetes)
  hosts: kubernetes_master
  become: true
  vars:
    - github_account: clincha
    - github_repo: streaming
    - runner_state: absent
    - runner_user: kubernetes
    - runner_dir: /usr/local/bin/github-runner
    - runner_labels:
        - "{{ site }}"
        - "kubernetes"
    - install_tools: false
  roles:
    - role: monolithprojects.github_actions_runner

- name: Setup github runners (proxy-kubernetes)
  hosts: kubernetes_master
  become: true
  vars:
    - github_account: clincha
    - github_repo: proxy
    - runner_state: absent
    - runner_user: kubernetes
    - runner_dir: /usr/local/bin/github-runner-proxy-kubernetes
    - runner_labels:
        - "{{ site }}"
        - "kubernetes"
    - install_tools: false
  roles:
    - role: monolithprojects.github_actions_runner