name: ansible

on:
  workflow_dispatch:

jobs:
  bristol:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install Galaxy requirements
        working-directory: Ansible
        run: |
          ansible-galaxy install -r galaxy-requirements.yml

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.ANSIBLE_PK }}

      - name: Run Ansible
        working-directory: Ansible
        env:
          PROXMOX_PASSWORD: ${{ secrets.ANSIBLE_PROXMOX_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          CLINCHA_PASSWORD: ${{ secrets.CLINCHA_PASSWORD }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
        run: |
          ansible-playbook site.yml --inventory bristol.proxmox.yml
