name: ansible

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5,10,15,20 * * *"

jobs:
  ansible-edinburgh:
    runs-on: [self-hosted, bristol]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@2.6.0
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          requirements: galaxy-requirements.yml
          options: |
            --inventory edinburgh.proxmox.yml
        env:
          PROXMOX_PASSWORD: ${{ secrets.ROOT_PROXMOX_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          CLINCHA_PASSWORD: ${{ secrets.CLINCHA_PASSWORD }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

  ansible-bristol:
    needs:
      - ansible-edinburgh
    runs-on: [self-hosted, edinburgh]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@2.6.0
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          requirements: galaxy-requirements.yml
          options: |
            --inventory bristol.proxmox.yml
        env:
          PROXMOX_PASSWORD: ${{ secrets.ROOT_PROXMOX_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          CLINCHA_PASSWORD: ${{ secrets.CLINCHA_PASSWORD }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}