name: clinch-home ansible nightly

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ansible-nightly:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: Site
        run: cd Ansible && ansible-playbook -vv -i inventory.proxmox.yml site.yml --key-file id_rsa -e proxmox_password='{{ lookup("env", "ANSIBLE_PASSWORD") }}'
        env:
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}

