name: ansible

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ansible:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa && dos2unix id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: ansible-playbook
        run: ansible-playbook -i inventory.proxmox.yml site.yml --key-file ../id_rsa
        working-directory: Ansible
        env:
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          PROXMOX_TOKEN_SECRET: ${{ secrets.ANSIBLE_PROXMOX_TOKEN_SECRET }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}

