name: ansible

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          options: |
            --inventory inventory.yml
            --verbose
        env:
          PROXMOX_TOKEN_SECRET: ${{ secrets.ANSIBLE_PROXMOX_TOKEN_SECRET }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}