name: ansible

on:
  push:
    branches:
      - '*'
  #  schedule:
  #    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: Install dependencies
        run: "ll /usr/bin | grep pip"

      - name: ansible-galaxy
        run: "ansible-galaxy collection install community.general"

      - name: ansible-playbook
        run: "ansible-playbook -vvvv -i inventory.proxmox.yml site.yml --key-file ../id_rsa"
        working-directory: Ansible
        env:
#          ANSIBLE_CONFIG: Ansible/ansible.cfg
          PROXMOX_TOKEN_SECRET: ${{ secrets.ANSIBLE_PROXMOX_TOKEN_SECRET }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}