name: create

on:
#  push:
#    branches:
#      - '*'
#  schedule:
#    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform initialise
        run: terraform init
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}

      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}

  ansible:
    runs-on: ubuntu-latest
    needs:
      - terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          options: |
            --inventory inventory.yml
            --verbose
        env:
          PROXMOX_TOKEN_SECRET: ${{ secrets.ANSIBLE_PROXMOX_TOKEN_SECRET }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}