name: create

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on:
      - self-hosted
      - init
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform initialise
        run: terraform init
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}

      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}

  ansible-edinburgh:
    runs-on: [self-hosted, init]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          requirements: galaxy-requirements.yml
          options: |
            --inventory edinburgh.proxmox.yml
        env:
          PROXMOX_PASSWORD: ${{ secrets.ROOT_PROXMOX_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          CLINCHA_PASSWORD: ${{ secrets.CLINCHA_PASSWORD }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

  ansible-bristol:
    needs:
      - ansible-edinburgh
    runs-on: [self-hosted, init]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: site.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          requirements: galaxy-requirements.yml
          options: |
            --inventory bristol.proxmox.yml
        env:
          PROXMOX_PASSWORD: ${{ secrets.ROOT_PROXMOX_PASSWORD }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          CLINCHA_PASSWORD: ${{ secrets.CLINCHA_PASSWORD }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}