name: elk

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  deploy-ELK:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: Create kubeconfig file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./kubeconfig
          contents: ${{ secrets.KUBECONFIG }}
          write-mode: overwrite

      - name: Ansible dependencies
        run: ansible-galaxy install elastic.beats,v7.15.0

      - name: ELK stack
        run: kubectl apply -f Kubernetes/Manifests/ELK

      - name: Metricbeat (Kubernetes)
        run: kubectl apply -f Kubernetes/Manifests/metricbeat-kubernetes.yaml

      - name: Metricbeat (Physical)
        run: ansible-playbook -i Ansible/inventory.yml --key-file id_rsa Ansible/elastic-stack/metricbeat.yml