name: elk

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  deploy-ELK:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create kubeconfig file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./kubeconfig
          contents: ${{ secrets.KUBECONFIG }}
          write-mode: overwrite

      - name: create ssh key
        run: 'echo "$ANSIBLE_PK" > id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: install ansible dependencies
        run: ansible-galaxy install elastic.beats,v7.15.0

      - name: deploy elk stack
        run: kubectl apply -f Kubernetes/Manifests/ELK --kubeconfig ./kubeconfig

      - name: deploy metricbeat (Kubernetes)
        run: kubectl apply -f Kubernetes/Manifests/metricbeat-kubernetes.yaml --kubeconfig ./kubeconfig

      - name: deploy metricbeat (Physical)
        run: ansible-playbook -i Ansible/inventory.yml --key-file id_rsa Ansible/elastic-stack/metricbeat.yml