name: kubernetes-infrastructure

on:
  workflow_dispatch:
  push:

jobs:
  apply-infrastructure:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: apply storage configuration
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/storage/csi-config-map.yml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
