name: kubernetes-infrastructure

on:
  workflow_dispatch:
  push:

jobs:
  apply-infrastructure:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Create kube config file from base64-encoded secret
        env:
          KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG_BASE64" | base64 --decode > kube_config
          export KUBE_CONFIG=$(pwd)/kube_config

      - name: Deploy configuration to kubernetes
        run: |
          kubectl apply -f csi-config-map.yml

      - name: Cleanup job
        run: |
          echo "Cleaning up resources"
          rm -rf kube_config
        if: always()
