name: nginx-proxy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Docker Build, Tag & Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: clincha/nginx-proxy
          tags: latest, v1.0
          registry: docker.io
          dockerfile: images/nginx-proxy/Dockerfile
          directory: images/nginx-proxy
          username: clincha
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-proxy-clinch-home:
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create kubeconfig file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./kubeconfig
          contents: ${{ secrets.KUBECONFIG }}
          write-mode: overwrite

      - name: install ansible dependencies
        run: ansible-galaxy install elastic.beats,v7.15.0

      - name: deploy nginx-proxy
        run: kubectl apply -f Kubernetes/Manifests/nginx-proxy.yaml --kubeconfig ./kubeconfig