name: packer-build

on:
  workflow_dispatch:
  push:

jobs:
  bri-s-01:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: packer build (bri-s-01)
        working-directory: packer
        run: |
          /usr/bin/packer build \
          -var "ansible_ssh_password=${{ secrets.ANSIBLE_PASSWORD }}" \
          -var "proxmox_api_token_secret=${{ secrets.PACKER_BRISTOL_PROXMOX_TOKEN_SECRET }}" \
          -var "vm_name=${{ github.run_id }}" \
          -var-file="bri-s-01.pkrvars.hcl" \
          .
