name: packer

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  packer:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: Site
        run: packer build .
        working-directory: packer
