name: packer

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: Site
        run: packer build -var "ansible_ssh_password=$ANSIBLE_PASSWORD" -var "proxmox_api_token_secret=$PROXMOX_TOKEN_SECRET" -var-file="credentials.pkrvars.hcl" .
        working-directory: packer
        env:
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          PROXMOX_TOKEN_SECRET: ${{ secrets.PACKER_PROXMOX_TOKEN_SECRET }}
