name: terraform-plan

on:
  workflow_dispatch:

jobs:
  terraform:
    env:
      ARM_TENANT_ID: "5bdbf6b9-7155-49e5-a3ce-f265fd5ec77e"
      ARM_CLIENT_ID: "6dbca134-0413-45d7-82ae-9359eba597ad"
      ARM_SUBSCRIPTION_ID: "c6ff6270-64cf-40d6-ae87-e11cca58de61"
      ARM_CLIENT_CERTIFICATE: ${{ secrets.ARM_CLIENT_CERTIFICATE }}
      ARM_CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.ARM_CLIENT_CERTIFICATE_PASSWORD }}
    runs-on: [ self-hosted, init ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: terraform initialise
        working-directory: terraform
        run: terraform init

      - name: terraform plan
        working-directory: terraform
        run: |
          /usr/bin/terraform plan \
            -var="ansible_id_rsa=${{ secrets.ANSIBLE_PK }}" \
            -var="bristol_proxmox_token_secret=${{ secrets.TERRAFORM_BRISTOL_PROXMOX_TOKEN_SECRET }}"
