name: terraform-apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform initialise
        working-directory: terraform
        run: terraform init

      - name: terraform apply
        working-directory: terraform
        run: |
          /usr/bin/terraform apply \
            --auto-approve \
            -var="ansible_id_rsa=${{ secrets.ANSIBLE_PK }}" \
            -var="edinburgh_proxmox_token_secret=${{ secrets.TERRAFORM_EDINBURGH_PROXMOX_TOKEN_SECRET }}" \
            -var="bristol_proxmox_token_secret=${{ secrets.TERRAFORM_BRISTOL_PROXMOX_TOKEN_SECRET }}"