name: terraform-destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ansible teardown
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: teardown.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          options: |
            --inventory inventory.yml
            --verbose
        env:
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform initialise
        run: terraform init
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}

      - name: terraform destroy
        run: terraform destroy -auto-approve
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}
