name: terraform-destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH key
        run: 'echo "$ANSIBLE_PK" > id_rsa && chmod 600 id_rsa'
        shell: bash
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}

      - name: ansible teardown
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: teardown.yml
          directory: Ansible
          key: ${{ secrets.ANSIBLE_PK }}
          options: |
            --inventory inventory.yml
            --verbose
        env:
          REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}

      - name: terraform apply
        run: terraform init && terraform destroy -auto-approve
        working-directory: terraform
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.TERRAFORM_PROXMOX_TOKEN_SECRET }}
