name: test

on:
  push:
  workflow_dispatch:

jobs:
  ansible-edinburgh:
    runs-on: [self-hosted, edinburgh]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: test
        run: echo $ANSIBLE_PK >> ~/ansible.key
        env:
          ANSIBLE_PK: ${{ secrets.ANSIBLE_PK }}
